# angular.module "sandbox"
#   .controller "PostsCtrl", ($scope, Post) ->
# angular.module 'sandbox',[]
angular.module 'sandbox'
  .controller 'PostsCtrl', ($scope, Item) ->
    $scope.addPost =(post) ->
      if Item.save post
        $scope.posts.push(post)
        $scope.Item = {}

    $scope.removePost =(post) ->
      console.debug post
      Item.delete { id: post.id }

    # $scope.post = Item.get({ id: $scope.id }, ->
    #   # console.log post
    #   return
    # )
    # get() returns a single entry
    $scope.posts = Item.query(->
      # console.log posts
      return
    )
    # #query() returns all the entries
    $scope.post = new Item
    # #You can instantiate resource class
    # $scope.post.title = 'some data'
    # Item.save $scope.post, ->
    #   #data saved. do something here.
    #   return
    #saves an entry. Assuming $scope.entry is the Entry object
    return

  # ---
  # generated by js2coffee 2.2.0
